#!/bin/bash

. $(find ~/ -maxdepth 1 -type f -name '.bash_profile')

if (($# > 0))
then
	token=$1
else
	token=1
fi

day=$(date --date=$token' days ago' '+%d')
month=$(date --date=$token' days ago' '+%m')
year=$(date --date=$token' days ago' '+%Y')

subCDRTable=SUB_CDR_${month}_${day}
delCDRTable=DEL_CDR_${month}_${day}
rptDate="${year}-${month}-${day}"

echo "[ $(date '+%d-%m-%Y %H:%M:%S') ] SUB_CDR - ${subCDRTable} DEL_CDR - ${delCDRTable} RPT_DATE - ${rptDate}"

mysql-ib -ucmsuser -pcmsuser -P5029 -h127.0.0.1 CMS_CDR -Ae "INSERT INTO RPT_SUBMIT_DELIVERY_FACT_IB (CDR_DATE, CIRCLE_ID, CAMPAIGN_CIRCLE_ID, OPERATOR_ID, TASK_ID, TASK_NAME, INTERFACE_ID, SMSC_ID, CHANNEL_ID, CP_ACCOUNT_ID, USER_ID, SCHDULE_USER_NAME, STATUS_CODE, SUBMIT_COUNT, SENDER_ID, SCHEDULED_COUNT) (SELECT  SUBMIT_DATE ddate, LEVEL_CIRCLE_ID,CIRCLE_ID,OPERATOR_ID,TASK_ID,FIELD15 TASK_NAME, INTERFACE_ID, SMSC_ID, FIELD6, FIELD10, FIELD12 USER_ID, FIELD9 USER_NAME, STATUS_CODE, COUNT(*), OA, SUM(CASE WHEN FIELD24 = 1 THEN 1 ELSE 0 END) SCHEDULED_COUNT FROM ${subCDRTable} CDR GROUP BY ddate, LEVEL_CIRCLE_ID, CIRCLE_ID, OPERATOR_ID, TASK_ID, TASK_NAME, INTERFACE_ID, SMSC_ID, FIELD6, FIELD10, USER_ID, FIELD9, STATUS_CODE,OA);"

mysql-ib -ucmsuser -pcmsuser -P5029 -h127.0.0.1 CMS_CDR -Ae "INSERT INTO RPT_SUBMIT_DELIVERY_FACT_IB (CDR_DATE, CIRCLE_ID, CAMPAIGN_CIRCLE_ID, OPERATOR_ID, TASK_ID, TASK_NAME, INTERFACE_ID, SMSC_ID, CHANNEL_ID, CP_ACCOUNT_ID, USER_ID, SCHDULE_USER_NAME, STATUS_CODE, DEL_STATUS, DELIVERY_COUNT,SENDER_ID) (SELECT SUB.SUBMIT_DATE ddate, LEVEL_CIRCLE_ID, SUB.CIRCLE_ID, OPERATOR_ID, TASK_ID, FIELD15 TASK_NAME, INTERFACE_ID, SUB.SMSC_ID, FIELD6, FIELD10, FIELD12 USER_ID, FIELD9 USER_NAME, STATUS_CODE, DEL.STATUS_ID, COUNT(*),OA FROM ${subCDRTable} SUB , (SELECT ACK_ID ACK_ID, MIN(STATUS_ID) STATUS_ID FROM ${delCDRTable} GROUP BY ACK_ID )DEL WHERE SUB.ACK_ID = DEL.ACK_ID GROUP BY ddate, LEVEL_CIRCLE_ID, SUB.CIRCLE_ID, OPERATOR_ID, TASK_ID, TASK_NAME, INTERFACE_ID, SUB.SMSC_ID, FIELD6, FIELD10, FIELD12, FIELD9, STATUS_CODE, DEL.STATUS_ID,SUB.OA);"

mysql-ib -ucmsuser -pcmsuser -P5029 -h127.0.0.1 CMS_CDR -Ae "INSERT INTO RPT_SUBMIT_DELIVERY_FACT_IB (CDR_DATE, CIRCLE_ID, CAMPAIGN_CIRCLE_ID, OPERATOR_ID, TASK_ID, TASK_NAME, INTERFACE_ID, SMSC_ID, CHANNEL_ID, CP_ACCOUNT_ID, USER_ID, SCHDULE_USER_NAME, STATUS_CODE, DEL_STATUS, DELIVERY_COUNT,SENDER_ID) (SELECT CDR_DATE, CIRCLE_ID, CAMPAIGN_CIRCLE_ID, OPERATOR_ID, TASK_ID, TASK_NAME, INTERFACE_ID, SMSC_ID, CHANNEL_ID, CP_ACCOUNT_ID, USER_ID, SCHDULE_USER_NAME, STATUS_CODE, '-1', SUM(IFNULL(SUBMIT_COUNT,0))-SUM(IFNULL(DELIVERY_COUNT,0)) CNT,SENDER_ID FROM RPT_SUBMIT_DELIVERY_FACT_IB WHERE CDR_DATE='${rptDate}' AND STATUS_CODE = 0 GROUP BY  CDR_DATE, CIRCLE_ID, CAMPAIGN_CIRCLE_ID, OPERATOR_ID, TASK_ID, TASK_NAME, INTERFACE_ID, SMSC_ID,SENDER_ID, CHANNEL_ID, CP_ACCOUNT_ID, USER_ID, SCHDULE_USER_NAME, STATUS_CODE, '-1');"

#mysql-ib -ucmsuser -pcmsuser -P5029 -h127.0.0.1 CMS_CDR -Ae "INSERT INTO RPT_SUBMIT_DELIVERY_MONTH_FACT_IB (CDR_DATE, SCHDULE_USER_NAME, USER_ID, CHANNEL_ID, INTERFACE_ID, TOTAL_SUBMIT, SUBMIT_SUCCCESS, SUBMIT_FAIL_DND, SUBMIT_FAIL, DELIVERY_SUCCCESS, DEIVERY_FAIL, DEIVERY_NOT_RECEVED, CDR_MONTH, CDR_YEAR) SELECT  CDR_DATE, SCHDULE_USER_NAME, USER_ID, CHANNEL_ID, INTERFACE_ID, SUM(SUBMIT_COUNT) TOTAL_SUBMIT,  SUM(CASE WHEN STATUS_CODE = 0 THEN SUBMIT_COUNT ELSE 0 END) SUBMIT_SUCCCESS,  SUM(CASE WHEN STATUS_CODE = 168 THEN SUBMIT_COUNT ELSE 0 END) SUBMIT_FAIL_DND, SUM(CASE WHEN STATUS_CODE NOT IN (0, 168) THEN SUBMIT_COUNT ELSE 0 END) SUBMIT_FAIL, SUM(CASE WHEN (STATUS_CODE = 0 AND DEL_STATUS = 0) THEN DELIVERY_COUNT ELSE 0 END) DEL_SUCCESS,  SUM(CASE WHEN (STATUS_CODE = 0  AND DEL_STATUS NOT IN ('0', '-1')) THEN DELIVERY_COUNT ELSE 0 END) DEL_FAILURE, SUM(CASE WHEN (STATUS_CODE = 0  AND DEL_STATUS = '-1') THEN DELIVERY_COUNT ELSE 0 END) DEL_NOT_RECIVED, MONTH(CDR_DATE), YEAR(CDR_DATE) FROM CMS_CDR.RPT_SUBMIT_DELIVERY_FACT_IB WHERE CDR_DATE = DATE_SUB(CURDATE(), INTERVAL ${token} DAY) AND SCHDULE_USER_NAME IS NOT NULL GROUP BY CDR_DATE, SCHDULE_USER_NAME, USER_ID, CHANNEL_ID, INTERFACE_ID ORDER BY CDR_DATE;"

echo "[ $(date '+%d-%m-%Y %H:%M:%S') ] Completed RPT_SUBMIT_DELIVERY_FACT_IB Data Population."
