#!/bin/bash

if (($# == 1))
then
        noOfDays=$1
else
        noOfDays=1
fi

day=$(date --date=${noOfDays}' days ago' '+%d')
month=$(date --date=${noOfDays}' days ago' '+%m')
year=$(date --date=${noOfDays}' days ago' '+%Y')

if [ -f /home/cmsuser/Scripts/.POPULATE_ONM_CAMPAIGN_SUBMIT_DELIVERY_SUMMARY_FACT ]
then
        exit 0
fi

touch /home/cmsuser/Scripts/.POPULATE_ONM_CAMPAIGN_SUBMIT_DELIVERY_SUMMARY_FACT
. $(find ~/ -maxdepth 1 -type f -iname '.bash_profile')

connectionString="mysql-ib -ucmsuser -pcmsuser -h127.0.0.1 -P5029 --table CMS_CDR -Ae "
insertSQLString="INSERT INTO ONM_CAMPAIGN_SUBMIT_DELIVERY_SUMMARY_FACT_IB (CDR_DATE, SCHDULE_USER_NAME, INTERFACE_ID, SMSC_ID, CHANNEL_ID, TOTAL_SUBMIT_COUNT, TOTAL_SUBMIT_SUCCESS_COUNT, TOTAL_SUBMIT_FAILURE_COUNT, TOTAL_DELIVERY_COUNT, TOTAL_DELIVERY_SUCCESS_COUNT, TOTAL_DELIVERY_FAILURE_COUNT, TOTAL_DELIVERY_NOTRECEIVED_COUNT) SELECT CDR_DATE, SCHDULE_USER_NAME, INTERFACE_ID, SMSC_ID, CHANNEL_ID, SUM(SUBMIT_COUNT) TOTAL_SUBMIT_COUNT, SUM(CASE WHEN STATUS_CODE = 0 THEN SUBMIT_COUNT ELSE 0 END) TOTAL_SUBMIT_SUCCESS_COUNT, (SUM(SUBMIT_COUNT) - SUM(CASE WHEN STATUS_CODE = 0 THEN SUBMIT_COUNT ELSE 0 END)) TOTAL_SUBMIT_FAILURE_COUNT, SUM(CASE WHEN STATUS_CODE = 0 AND DEL_STATUS <> '-1' THEN DELIVERY_COUNT ELSE 0 END) TOTAL_DELIVERY_COUNT, SUM(CASE WHEN (STATUS_CODE = 0  AND DEL_STATUS = '0') THEN DELIVERY_COUNT ELSE 0 END) TOTAL_DELIVERY_SUCCESS_COUNT, (SUM(CASE WHEN STATUS_CODE = 0 AND DEL_STATUS <> '-1' THEN DELIVERY_COUNT ELSE 0 END) - SUM(CASE WHEN (STATUS_CODE = 0  AND DEL_STATUS = '0') THEN DELIVERY_COUNT ELSE 0 END)) TOTAL_DELIVERY_FAILURE_COUNT, SUM(CASE WHEN STATUS_CODE = 0 AND DEL_STATUS = '-1' THEN DELIVERY_COUNT ELSE 0 END) TOTAL_DELIVERY_NOTRECEIVED_COUNT FROM CMS_CDR.RPT_SUBMIT_DELIVERY_FACT_IB WHERE CDR_DATE = '${year}-${month}-${day}' GROUP BY USER_ID, INTERFACE_ID, SMSC_ID, CHANNEL_ID ORDER BY SCHDULE_USER_NAME;"
echo "SQL String :: ${insertSQLString}"
${connectionString} "${insertSQLString}"
rm -f /home/cmsuser/Scripts/.POPULATE_ONM_CAMPAIGN_SUBMIT_DELIVERY_SUMMARY_FACT
